# Docker configuration backend
providers:
    docker:
      defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

# API and dashboard configuration
api:
    insecure: true

entryPoints:
    web:
      address: ":80"

    websecure:
      address: ":443"

certificatesResolvers:
    myresolver:
        acme:
            email: admin@example.com
            storage: acme.json
            # Staging server for testing, comment when deploying to prod
            caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
            #tlsChallenge:

            # Optional
            httpChallenge:
                entryPoint: web